import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type Obj=Record<string,unknown>; type Rpc={id?:string|number|null;method?:string;params?:{name?:string;arguments?:Obj}};
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,mcp-protocol-version,mcp-session-id","Access-Control-Allow-Methods":"POST,OPTIONS"};
const header={...cors,"Content-Type":"application/json"};
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,"0")).join("");
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:header});
const result=(id:Rpc["id"],value:unknown)=>out({jsonrpc:"2.0",id:id??null,result:value});
const fail=(id:Rpc["id"],message:string,code=-32000)=>out({jsonrpc:"2.0",id:id??null,error:{code,message}});
const tool=(value:unknown)=>({content:[{type:"text",text:JSON.stringify(value,null,2)}],structuredContent:value});
const error=(message:string)=>({content:[{type:"text",text:message}],isError:true});
const bounded=(value:unknown,fallback=25)=>Math.max(1,Math.min(100,Number(value)||fallback));
const operational=new Set(["admin","operational","operational_supervisor","operational_manager","coordinator"]);
const planningEditors=new Set(["admin","commercial","operational_supervisor","operational_manager"]);
const teamManagers=new Set(["admin","operational_supervisor","operational_manager","coordinator"]);
const appRoles=new Set(["admin","commercial","operational_supervisor","operational_manager","operational","ti","coordinator","viewer"]);
const clonePlanning=(source:any)=>{if(!source||typeof source!=="object")return null;const copy=structuredClone(source);copy.completedBlocks={};copy.store={...(copy.store||{}),unit:"",preStart:"",preEnd:"",inventoryStart:"",inventoryEnd:"",headcount:""};copy.responsibilities=(copy.responsibilities||[]).map((row:any)=>({...row,person:"",notes:""}));copy.logistics={...(copy.logistics||{}),notes:"",transports:(copy.logistics?.transports||[]).map((row:any)=>({...row,date:"",time:"",passengers:"",quantity:"",notes:""})),accommodations:(copy.logistics?.accommodations||[]).map((row:any)=>({...row,guests:"",rooms:"",checkIn:"",checkOut:"",count:"",notes:""}))};for(const key of ["clientEquipment","contagemEquipment"])copy[key]={...(copy[key]||{}),notes:"",rows:(copy[key]?.rows||[]).map((row:any)=>({...row,date:"",quantity:"",status:"Solicitado",notes:""}))};copy.preCount={...(copy.preCount||{}),notes:"",rows:(copy.preCount?.rows||[]).map((row:any)=>({...row,date:"",time:"",team:"",count:"",notes:""}))};copy.days=(copy.days||[]).map((day:any)=>({...day,date:"",headcount:"",notes:"",areas:(day.areas||[]).map((area:any)=>({...area,startsAt:"",headcount:"",notes:"",roles:(area.roles||[]).map((role:any)=>({...role,count:"",names:""})),activities:(area.activities||[]).map((activity:any)=>({...activity,notes:""}))}))}));for(const key of Object.keys(copy.checklists||{}))copy.checklists[key]=(copy.checklists[key]||[]).map((item:any)=>{const next={...item,done:false};delete next.completedAt;delete next.completedBy;return next});return copy};

const tools=[
  ["contagem_overview","Resumo operacional e permissões da conexão.",{},[]],
  ["contagem_list_projects","Lista operações por etapa com paginação.",{status:{type:"string"},search:{type:"string",maxLength:120},limit:{type:"integer",minimum:1,maximum:100},offset:{type:"integer",minimum:0,maximum:10000}},[]],
  ["contagem_get_project","Detalhe consolidado de uma operação.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_get_export_data","Retorna dados completos para gerar PDF, Excel ou relatório.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_list_tasks","Lista tarefas por status, operação ou responsável.",{project_id:{type:"string"},status:{type:"string"},search:{type:"string",maxLength:120},limit:{type:"integer",minimum:1,maximum:100}},[]],
  ["contagem_list_calendar","Lista operações com início de inventário em um intervalo.",{start_date:{type:"string"},end_date:{type:"string"}},[]],
  ["contagem_list_settings","Lista campos, modelos de tarefas e catálogos configuráveis.",{},[]],
  ["contagem_create_request","Cria ou duplica solicitação de forma idempotente.",{idempotency_key:{type:"string"},cnpj:{type:"string"},legal_name:{type:"string"},trade_name:{type:"string"},address:{type:"string"},contact_name:{type:"string"},contact_email:{type:"string"},contact_phone:{type:"string"},inventory_type:{type:"string"},layout_system:{type:"string"},ti_contact_name:{type:"string"},ti_contact_email:{type:"string"},ti_contact_phone:{type:"string"},requires_dimensioning:{type:"boolean"},source_project_id:{type:"string"},field_values:{type:"array",items:{type:"object"}}},["idempotency_key","cnpj","legal_name","contact_name","contact_email"]],
  ["contagem_start_dimensioning","Move uma solicitação para Dimensionamento.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_save_dimensioning","Salva cenários, opção selecionada e visitas.",{project_id:{type:"string"},options:{type:"array",items:{type:"object"}},selected_option_id:{type:["string","null"]},visit_starts:{type:"array",items:{type:"string"}},notes:{type:"string"}},["project_id","options","visit_starts"]],
  ["contagem_complete_dimensioning","Conclui dimensionamento e envia para TI.",{project_id:{type:"string"},notes:{type:"string"}},["project_id"]],
  ["contagem_save_ti","Salva dados técnicos e visita selecionada.",{project_id:{type:"string"},system_name:{type:"string"},ti_contact_name:{type:"string"},ti_contact_email:{type:"string"},ti_contact_phone:{type:"string"},notes:{type:"string"},selected_date_option_id:{type:["string","null"]}},["project_id"]],
  ["contagem_approve_ti","Aprova TI e libera Planejamento.",{project_id:{type:"string"},system_name:{type:"string"},notes:{type:"string"}},["project_id"]],
  ["contagem_save_planning","Salva todos os blocos e checklists.",{project_id:{type:"string"},content:{type:"object"},completion_percentage:{type:"number",minimum:0,maximum:100}},["project_id","content"]],
  ["contagem_approve_planning","Aprova planejamento e conclui operação.",{project_id:{type:"string"},content:{type:"object"},completion_percentage:{type:"number",minimum:0,maximum:100}},["project_id","content","completion_percentage"]],
  ["contagem_sync_tasks","Gera ou recalcula tarefas aplicáveis.",{project_id:{type:"string"},inventory_start:{type:["string","null"]}},["project_id"]],
  ["contagem_update_task","Atualiza responsável, prazo ou status.",{task_id:{type:"string"},status:{type:"string",enum:["pending","in_progress","completed","waived"]},responsible_name:{type:"string",maxLength:160},due_at:{type:["string","null"]},set_due:{type:"boolean"}},["task_id"]],
  ["contagem_upsert_custom_field","Cria ou atualiza campo. Somente admin.",{field_id:{type:["string","null"]},field_key:{type:"string"},label:{type:"string"},field_type:{type:"string",enum:["text","textarea","number","date","email","phone","select","checkbox"]},required:{type:"boolean"},active:{type:"boolean"},stage:{type:"string",enum:["request","dimensioning","ti","planning","calendar"]},show_when_dimensioning:{type:"boolean"},sort_order:{type:"integer"},options:{type:"array",items:{type:"string"}},placeholder:{type:"string"},help_text:{type:"string"}},["label"]],
  ["contagem_delete_custom_field","Exclui campo não sistêmico. Somente admin.",{field_id:{type:"string"}},["field_id"]],
  ["contagem_upsert_task_template","Gerencia modelo de tarefa. Somente admin.",{template_id:{type:["string","null"]},title:{type:"string"},description:{type:"string"},inventory_type:{type:"string"},due_days_before_inventory:{type:["integer","null"]},responsible_role:{type:"string"},active:{type:"boolean"},sort_order:{type:"integer"}},["title"]],
  ["contagem_upsert_admin_catalog","Gerencia funções, atividades, equipamentos, blocos, tipos e etapas. Somente admin.",{catalog:{type:"string",enum:["roles","activities","equipment","blocks","inventory_types","workflow_stages"]},item:{type:"object"}},["catalog","item"]],
  ["contagem_upsert_checklist_template","Gerencia template e itens de checklist. Somente admin.",{template_id:{type:["string","null"]},name:{type:"string"},checklist_type:{type:"string",enum:["pre_inventory_visit","planning","final"]},inventory_type:{type:["string","null"]},active:{type:"boolean"},items:{type:"array",items:{type:"object"}}},["name","checklist_type","items"]],
  ["contagem_list_users","Lista o diretório de pessoas e papéis. Usuários ativos consultam; admin também vê inativos.",{},[]],
  ["contagem_list_team_assignments","Lista as pessoas alocadas em uma operação.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_save_team_assignment","Adiciona ou atualiza uma pessoa na equipe da operação.",{assignment_id:{type:["string","null"]},project_id:{type:"string"},user_id:{type:"string"},assignment_role:{type:"string"},team_type:{type:"string",enum:["internal","freelance","coordinator","support"]},status:{type:"string",enum:["planned","invited","confirmed","declined"]},shift:{type:["string","null"]},area:{type:["string","null"]},notes:{type:["string","null"]}},["project_id","user_id","assignment_role"]],
  ["contagem_remove_team_assignment","Remove uma pessoa da equipe da operação.",{assignment_id:{type:"string"}},["assignment_id"]],
  ["contagem_invite_user","Convida usuário, registra cargo e define papéis. Somente admin.",{email:{type:"string"},full_name:{type:"string"},job_title:{type:["string","null"]},roles:{type:"array",items:{type:"string"}}},["email","roles"]],
  ["contagem_set_user_access","Atualiza nome, cargo, status e papéis de usuário. Somente admin.",{user_id:{type:"string"},full_name:{type:"string"},job_title:{type:["string","null"]},active:{type:"boolean"},roles:{type:"array",items:{type:"string"}}},["user_id","roles"]],
  ["contagem_update_project_core","Edita cadastro-base e valores configuráveis com concorrência otimista.",{project_id:{type:"string"},expected_updated_at:{type:["string","null"]},project:{type:"object"},client:{type:"object"},contact:{type:"object"},field_values:{type:"array",items:{type:"object"}}},["project_id"]],
  ["contagem_manage_project_lifecycle","Cancela, arquiva, restaura ou atribui etapa customizada. Somente admin.",{project_id:{type:"string"},action:{type:"string",enum:["cancel","archive","restore","set_custom_stage","clear_custom_stage"]},reason:{type:"string"},stage_key:{type:["string","null"]}},["project_id","action"]]
].map(([name,description,properties,required])=>({name,title:String(name).replaceAll("_"," "),description,inputSchema:{type:"object",properties,required,additionalProperties:false},annotations:{readOnlyHint:!String(name).match(/_(create|start|save|complete|approve|sync|update|upsert|delete|invite|manage|set)_?/),destructiveHint:String(name).includes("delete")||String(name).includes("remove")||String(name).includes("lifecycle"),idempotentHint:true,openWorldHint:false}}));
const readTools=new Set(["contagem_overview","contagem_list_projects","contagem_get_project","contagem_get_export_data","contagem_list_tasks","contagem_list_calendar","contagem_list_settings","contagem_list_users","contagem_list_team_assignments"]);

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return out({error:"Use POST."},405);
  const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)return out({error:"Bearer obrigatório."},401);
  const url=Deno.env.get("SUPABASE_URL")!;const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
  const {data:connection}=await db.from("contagem_g4os_connections").select("id,owner_user_id,scopes").eq("token_hash",await sha256(token)).eq("active",true).maybeSingle();
  if(!connection)return out({error:"Credencial inválida ou revogada."},401);
  const [{data:roles},{data:profile}]=await Promise.all([db.from("user_roles").select("role").eq("user_id",connection.owner_user_id),db.from("profiles").select("active").eq("id",connection.owner_user_id).maybeSingle()]);const roleList=(roles??[]).map(row=>String(row.role));
  if(!profile?.active||!roleList.length)return out({error:"Usuário da conexão inativo ou sem perfil."},403);
  await db.from("contagem_g4os_connections").update({last_used_at:new Date().toISOString()}).eq("id",connection.id);
  let rpc:Rpc;try{rpc=await req.json()}catch{return fail(null,"JSON-RPC inválido",-32700)}
  if(rpc.method==="initialize")return result(rpc.id,{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"contagem-ops-mcp",version:"1.0.0"}});
  if(rpc.method==="notifications/initialized")return new Response(null,{status:202,headers:cors});
  const scopeList=Array.isArray(connection.scopes)?connection.scopes.map(String):[];const canRead=scopeList.includes("read");const canWrite=scopeList.includes("write");
  const scopedTools=tools.filter(item=>readTools.has(String(item.name))?canRead:canWrite);
  if(rpc.method==="tools/list")return result(rpc.id,{tools:scopedTools});
  if(rpc.method!=="tools/call")return fail(rpc.id,"Método não suportado",-32601);
  const name=rpc.params?.name||"";const args=rpc.params?.arguments||{};const started=Date.now();let operation=readTools.has(name)?"READ":"WRITE";
  const audit=async(success:boolean,details:Obj={})=>{await db.from("contagem_g4os_events").insert({connection_id:connection.id,actor_user_id:connection.owner_user_id,tool_name:name,operation,success,duration_ms:Date.now()-started,details})};
  try{
    if(!tools.some(item=>item.name===name))throw new Error("Ferramenta não encontrada.");
    if((readTools.has(name)&&!canRead)||(!readTools.has(name)&&!canWrite))throw new Error(`Escopo ${readTools.has(name)?"read":"write"} não autorizado para esta conexão.`);
    if(name==="contagem_overview"){
      const statuses=["received","awaiting_dimensioning","awaiting_ti","planning","confirmed"];const counts=Object.fromEntries(await Promise.all(statuses.map(async status=>[status,(await db.from("projects").select("id",{count:"exact",head:true}).eq("status",status).is("deleted_at",null)).count??0])));const payload={roles:roleList,scopes:connection.scopes,projects:counts};await audit(true);return result(rpc.id,tool(payload));
    }
    if(name==="contagem_list_projects"){
      const {data,error:queryError}=await db.rpc("g4os_list_projects",{p_actor_id:connection.owner_user_id,p_status:args.status||null,p_search:String(args.search||""),p_limit:bounded(args.limit),p_offset:Math.max(0,Number(args.offset)||0)});if(queryError)throw queryError;const payload=data||{items:[],total:0};await audit(true,{returned:Array.isArray(payload.items)?payload.items.length:0});return result(rpc.id,tool(payload));
    }
    if(name==="contagem_get_project"){
      const projectId=String(args.project_id||"");if(!projectId)throw new Error("project_id obrigatório.");const {data,error:queryError}=await db.from("projects").select("*,clients(*),dimensionings(*,dimensioning_options(*)),date_options(*),ti_validations(*),plannings(*),project_tasks(*),project_team_assignments(*)").eq("id",projectId).is("deleted_at",null).maybeSingle();if(queryError||!data)throw new Error("Operação não encontrada.");await audit(true);return result(rpc.id,tool(data));
    }
    if(name==="contagem_list_tasks"){
      const {data,error:queryError}=await db.rpc("g4os_list_tasks",{p_actor_id:connection.owner_user_id,p_project_id:args.project_id||null,p_status:args.status||null,p_search:String(args.search||""),p_limit:bounded(args.limit)});if(queryError)throw queryError;const payload=data||{items:[]};await audit(true,{returned:Array.isArray(payload.items)?payload.items.length:0});return result(rpc.id,tool(payload));
    }
    if(name==="contagem_list_calendar"){
      const {data,error:queryError}=await db.from("plannings").select("project_id,content,status,projects!inner(reference,status,deleted_at,date_options(*),clients(legal_name))").is("projects.deleted_at",null).limit(500);if(queryError)throw queryError;const start=String(args.start_date||"");const end=String(args.end_date||"");const items=(data??[]).filter((row:any)=>{const date=row.content?.store?.inventoryStart||"";return date&&(!start||date>=start)&&(!end||date<=end)}).map((row:any)=>({project_id:row.project_id,reference:row.projects?.reference,company:row.projects?.clients?.legal_name,status:row.projects?.status,inventory_start:row.content?.store?.inventoryStart,inventory_end:row.content?.store?.inventoryEnd,headcount:row.content?.store?.headcount,date_options:row.projects?.date_options||[],days:row.content?.days||[],responsibilities:row.content?.responsibilities||[],client_equipment:row.content?.clientEquipment||{},contagem_equipment:row.content?.contagemEquipment||{},content:row.content}));await audit(true,{returned:items.length});return result(rpc.id,tool({items}));
    }

    if(name==="contagem_get_export_data"){
      const projectId=String(args.project_id||"");const {data,error:queryError}=await db.from("projects").select("id,reference,status,inventory_type,clients(legal_name,trade_name,cnpj),dimensionings(*,dimensioning_options(*)),date_options(*),ti_validations(*),plannings(*),project_tasks(*),project_team_assignments(*)").eq("id",projectId).is("deleted_at",null).maybeSingle();if(queryError||!data)throw new Error("Operação não encontrada.");await audit(true);return result(rpc.id,tool({generated_at:new Date().toISOString(),project:data}));
    }
    if(name==="contagem_list_settings"){
      const settings=await Promise.all([db.from("custom_fields").select("*").eq("entity","project").order("sort_order"),db.from("task_templates").select("*").order("sort_order"),db.from("planning_role_catalog").select("*").order("sort_order"),db.from("planning_activity_catalog").select("*").order("sort_order"),db.from("equipment_catalog").select("*").order("name"),db.from("checklist_templates").select("*,checklist_template_items(*)"),db.from("inventory_type_catalog").select("*").order("sort_order"),db.from("planning_block_definitions").select("*").order("sort_order"),db.from("workflow_stage_catalog").select("*").order("sort_order")]);const firstError=settings.find(item=>item.error)?.error;if(firstError)throw firstError;await audit(true);return result(rpc.id,tool({custom_fields:settings[0].data,task_templates:settings[1].data,role_catalog:settings[2].data,activity_catalog:settings[3].data,equipment_catalog:settings[4].data,checklist_templates:settings[5].data,inventory_types:settings[6].data,planning_blocks:settings[7].data,workflow_stages:settings[8].data}));
    }
    if(name==="contagem_list_users"){
      const [profiles,userRoles]=await Promise.all([db.from("profiles").select("id,full_name,email,job_title,active,created_at,updated_at").order("full_name"),db.from("user_roles").select("user_id,role")]);if(profiles.error)throw profiles.error;if(userRoles.error)throw userRoles.error;const visible=roleList.includes("admin")?(profiles.data||[]):(profiles.data||[]).filter(item=>item.active);const users=visible.map(profile=>({...profile,roles:(userRoles.data||[]).filter(item=>item.user_id===profile.id).map(item=>item.role)}));await audit(true,{returned:users.length});return result(rpc.id,tool({users,can_manage:roleList.includes("admin")}));
    }
    if(name==="contagem_list_team_assignments"){
      const projectId=String(args.project_id||"");const {data:project}=await db.from("projects").select("id").eq("id",projectId).is("deleted_at",null).maybeSingle();if(!project)throw new Error("Operação não encontrada ou arquivada.");const [{data:assignments,error:assignmentError},{data:profiles,error:profileError}]=await Promise.all([db.from("project_team_assignments").select("*").eq("project_id",projectId).order("created_at"),db.from("profiles").select("id,full_name,email,job_title,active")]);if(assignmentError)throw assignmentError;if(profileError)throw profileError;const people=new Map((profiles||[]).map(item=>[item.id,item]));const items=(assignments||[]).map(item=>({...item,person:people.get(item.user_id)||null}));await audit(true,{returned:items.length});return result(rpc.id,tool({items}));
    }
    const actor=connection.owner_user_id;
    const activeProjectTools=new Set(["contagem_start_dimensioning","contagem_save_dimensioning","contagem_complete_dimensioning","contagem_save_ti","contagem_approve_ti","contagem_save_planning","contagem_approve_planning","contagem_sync_tasks","contagem_update_project_core"]);
    if(activeProjectTools.has(name)){const {data:activeProject}=await db.from("projects").select("id").eq("id",String(args.project_id||"")).is("deleted_at",null).maybeSingle();if(!activeProject)throw new Error("Operação não encontrada ou arquivada.");}
    if(name==="contagem_update_task"){const {data:activeTask}=await db.from("project_tasks").select("id,projects!inner(deleted_at)").eq("id",String(args.task_id||"")).is("projects.deleted_at",null).maybeSingle();if(!activeTask)throw new Error("Tarefa não encontrada ou operação arquivada.");}
    if(name==="contagem_start_dimensioning"){const {error:e}=await db.rpc("g4os_start_dimensioning",{p_actor_id:actor,p_project_id:String(args.project_id)});if(e)throw e;await audit(true);return result(rpc.id,tool({started:true}));}
    if(name==="contagem_save_dimensioning"){const {error:e}=await db.rpc("g4os_save_dimensioning_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_options:args.options||[],p_selected_option_id:args.selected_option_id||null,p_visit_starts:args.visit_starts||[],p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({saved:true}));}
    if(name==="contagem_complete_dimensioning"){const {error:e}=await db.rpc("g4os_complete_dimensioning",{p_actor_id:actor,p_project_id:String(args.project_id),p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({completed:true}));}
    if(name==="contagem_save_ti"){const {error:e}=await db.rpc("g4os_save_ti_validation_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_system_name:args.system_name||null,p_ti_contact_name:args.ti_contact_name||null,p_ti_contact_email:args.ti_contact_email||null,p_ti_contact_phone:args.ti_contact_phone||null,p_notes:args.notes||null,p_selected_date_option_id:args.selected_date_option_id||null});if(e)throw e;await audit(true);return result(rpc.id,tool({saved:true}));}
    if(name==="contagem_approve_ti"){const {error:e}=await db.rpc("g4os_approve_ti_validation",{p_actor_id:actor,p_project_id:String(args.project_id),p_system_name:args.system_name||null,p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({approved:true}));}
    if(name==="contagem_save_planning"){const {data,error:e}=await db.rpc("g4os_save_planning_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_content:args.content,p_completion_percentage:Number(args.completion_percentage)||0});if(e)throw e;await audit(true);return result(rpc.id,tool({planning_id:data}));}
    if(name==="contagem_approve_planning"){const {error:e}=await db.rpc("g4os_approve_planning",{p_actor_id:actor,p_project_id:String(args.project_id),p_content:args.content,p_completion_percentage:Number(args.completion_percentage)});if(e)throw e;await audit(true);return result(rpc.id,tool({approved:true}));}
    if(name==="contagem_sync_tasks"){const {data,error:e}=await db.rpc("g4os_sync_project_tasks",{p_actor_id:actor,p_project_id:String(args.project_id),p_inventory_start:args.inventory_start||null});if(e)throw e;await audit(true);return result(rpc.id,tool({affected:data}));}
    if(name==="contagem_update_task"){const {data,error:e}=await db.rpc("g4os_update_project_task",{p_actor_id:actor,p_task_id:String(args.task_id),p_status:args.status||null,p_responsible_name:args.responsible_name??null,p_due_at:args.due_at||null,p_set_due:Boolean(args.set_due||Object.prototype.hasOwnProperty.call(args,"due_at"))});if(e)throw e;await audit(true,{task_id:args.task_id});return result(rpc.id,tool(data));}
    if(name==="contagem_upsert_custom_field"){const {data,error:e}=await db.rpc("g4os_upsert_custom_field_v2",{p_actor_id:actor,p_field_id:args.field_id||null,p_field_key:args.field_key||null,p_label:String(args.label||""),p_field_type:args.field_type||"text",p_required:args.required??false,p_active:args.active??true,p_stage:args.stage||"request",p_show_when_dimensioning:args.show_when_dimensioning??false,p_sort_order:Number(args.sort_order)||0,p_options:args.options||[],p_placeholder:args.placeholder||null,p_help_text:args.help_text||null});if(e)throw e;await audit(true);return result(rpc.id,tool({field_id:data}));}
    if(name==="contagem_delete_custom_field"){const {error:e}=await db.rpc("g4os_delete_custom_field",{p_actor_id:actor,p_field_id:String(args.field_id)});if(e)throw e;await audit(true);return result(rpc.id,tool({deleted:true}));}
    if(name==="contagem_upsert_task_template"){const {data,error:e}=await db.rpc("g4os_upsert_task_template",{p_actor_id:actor,p_template_id:args.template_id||null,p_title:String(args.title||""),p_description:args.description||null,p_inventory_type:args.inventory_type||null,p_due_days_before_inventory:args.due_days_before_inventory??null,p_responsible_role:args.responsible_role||null,p_active:args.active??true,p_sort_order:Number(args.sort_order)||0});if(e)throw e;await audit(true);return result(rpc.id,tool({template_id:data}));}
    if(name==="contagem_upsert_admin_catalog"){const {data,error:e}=await db.rpc("g4os_upsert_admin_catalog",{p_actor_id:actor,p_catalog:String(args.catalog||""),p_item:args.item||{}});if(e)throw e;await audit(true);return result(rpc.id,tool(data));}
    if(name==="contagem_upsert_checklist_template"){const {data,error:e}=await db.rpc("g4os_upsert_checklist_template",{p_actor_id:actor,p_template_id:args.template_id||null,p_name:String(args.name||""),p_checklist_type:String(args.checklist_type||"planning"),p_inventory_type:args.inventory_type||null,p_active:args.active??true,p_items:args.items||[]});if(e)throw e;await audit(true);return result(rpc.id,tool(data));}
    if(name==="contagem_save_team_assignment"){if(!roleList.some(role=>teamManagers.has(role)))throw new Error("Seu perfil não pode editar a equipe da operação.");const projectId=String(args.project_id||"");const userId=String(args.user_id||"");const assignmentRole=String(args.assignment_role||"").trim();if(!projectId||!userId||!assignmentRole)throw new Error("project_id, user_id e assignment_role são obrigatórios.");const [{data:project},{data:targetProfile}]=await Promise.all([db.from("projects").select("id").eq("id",projectId).is("deleted_at",null).maybeSingle(),db.from("profiles").select("id,active").eq("id",userId).eq("active",true).maybeSingle()]);if(!project)throw new Error("Operação não encontrada ou arquivada.");if(!targetProfile)throw new Error("Pessoa não encontrada ou inativa.");const payload={project_id:projectId,user_id:userId,assignment_role:assignmentRole,team_type:String(args.team_type||"internal"),status:String(args.status||"planned"),shift:args.shift||null,area:args.area||null,notes:args.notes||null,assigned_by:actor,updated_at:new Date().toISOString()};let saved;if(args.assignment_id){const response=await db.from("project_team_assignments").update(payload).eq("id",String(args.assignment_id)).eq("project_id",projectId).select("*").single();if(response.error)throw response.error;saved=response.data}else{const response=await db.from("project_team_assignments").insert(payload).select("*").single();if(response.error)throw response.error;saved=response.data}await audit(true,{assignment_id:saved.id,project_id:projectId});return result(rpc.id,tool(saved));}
    if(name==="contagem_remove_team_assignment"){if(!roleList.some(role=>teamManagers.has(role)))throw new Error("Seu perfil não pode editar a equipe da operação.");const assignmentId=String(args.assignment_id||"");const {data:existing}=await db.from("project_team_assignments").select("id,project_id").eq("id",assignmentId).maybeSingle();if(!existing)throw new Error("Alocação não encontrada.");const {error:e}=await db.from("project_team_assignments").delete().eq("id",assignmentId);if(e)throw e;await audit(true,{assignment_id:assignmentId,project_id:existing.project_id});return result(rpc.id,tool({removed:true}));}
    if(name==="contagem_invite_user"){if(!roleList.includes("admin"))throw new Error("Somente administradores podem convidar usuários.");const email=String(args.email||"").trim().toLowerCase();const requestedRoles=Array.isArray(args.roles)?args.roles.map(String):[];if(!requestedRoles.length||requestedRoles.some(role=>!appRoles.has(role)))throw new Error("Informe ao menos um papel válido.");const {data:invited,error:inviteError}=await db.auth.admin.inviteUserByEmail(email,{data:{full_name:String(args.full_name||email)}});if(inviteError||!invited.user)throw inviteError||new Error("Convite não criado.");try{const profileResult=await db.from("profiles").upsert({id:invited.user.id,full_name:String(args.full_name||email),email,job_title:String(args.job_title||"").trim()||null,active:true},{onConflict:"id"});if(profileResult.error)throw profileResult.error;const {data,error:e}=await db.rpc("g4os_set_user_access",{p_actor_id:actor,p_user_id:invited.user.id,p_full_name:String(args.full_name||email),p_active:true,p_roles:requestedRoles});if(e)throw e;await audit(true,{user_id:invited.user.id});return result(rpc.id,tool(data));}catch(inviteSetupError){await db.auth.admin.deleteUser(invited.user.id);throw inviteSetupError;}}
    if(name==="contagem_set_user_access"){const userId=String(args.user_id);const {data,error:e}=await db.rpc("g4os_set_user_access",{p_actor_id:actor,p_user_id:userId,p_full_name:args.full_name||null,p_active:args.active??true,p_roles:Array.isArray(args.roles)?args.roles:[]});if(e)throw e;if(Object.prototype.hasOwnProperty.call(args,"job_title")){const titleResult=await db.from("profiles").update({job_title:String(args.job_title||"").trim()||null}).eq("id",userId);if(titleResult.error)throw titleResult.error;}await audit(true,{user_id:userId});return result(rpc.id,tool({...data,job_title:String(args.job_title||"").trim()||null}));}
    if(name==="contagem_update_project_core"){const {data,error:e}=await db.rpc("g4os_update_project_core",{p_actor_id:actor,p_project_id:String(args.project_id),p_expected_updated_at:args.expected_updated_at||null,p_project:args.project||{},p_client:args.client||{},p_contact:args.contact||{},p_field_values:args.field_values||[]});if(e)throw e;await audit(true,{project_id:args.project_id});return result(rpc.id,tool(data));}
    if(name==="contagem_manage_project_lifecycle"){const {data,error:e}=await db.rpc("g4os_manage_project_lifecycle",{p_actor_id:actor,p_project_id:String(args.project_id),p_action:String(args.action),p_reason:args.reason||null,p_stage_key:args.stage_key||null});if(e)throw e;await audit(true,{project_id:args.project_id,action:args.action});return result(rpc.id,tool(data));}
    if(name==="contagem_create_request"){
      if(!roleList.some(role=>planningEditors.has(role)))throw new Error("Seu perfil não pode criar solicitações.");const key=String(args.idempotency_key||"");if(!/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(key))throw new Error("idempotency_key deve ser um UUID.");let planningContent=null;if(args.source_project_id){const sourceId=String(args.source_project_id);const {data:sourceProject}=await db.from("projects").select("id").eq("id",sourceId).is("deleted_at",null).maybeSingle();if(!sourceProject)throw new Error("Operação de origem não encontrada ou arquivada.");const {data:source,error:sourceError}=await db.from("plannings").select("content").eq("project_id",sourceId).maybeSingle();if(sourceError||!source)throw new Error("Planejamento de origem não encontrado.");planningContent=clonePlanning(source.content)}const {data,error:e}=await db.rpc("g4os_create_project_request",{p_actor_id:actor,p_request_key:key,p_cnpj:String(args.cnpj||"").replace(/\D/g,""),p_cnpj_raw:String(args.cnpj||""),p_legal_name:String(args.legal_name||""),p_trade_name:args.trade_name||null,p_address:args.address||null,p_contact_name:String(args.contact_name||""),p_contact_email:String(args.contact_email||""),p_contact_phone:args.contact_phone||null,p_inventory_type:args.inventory_type||null,p_layout_system:args.layout_system||null,p_ti_contact_name:args.ti_contact_name||null,p_ti_contact_email:args.ti_contact_email||null,p_ti_contact_phone:args.ti_contact_phone||null,p_requires_dimensioning:args.requires_dimensioning!==false,p_operational_notes:args.source_project_id?`Modelo copiado de ${args.source_project_id}`:"Criada pelo G4 OS",p_field_values:args.field_values||[],p_planning_content:planningContent});if(e)throw e;await audit(true,{project_id:data});return result(rpc.id,tool({project_id:data}));
    }
    throw new Error("Ferramenta não encontrada.");
  }catch(cause){const message=cause instanceof Error?cause.message:"Falha ao executar ferramenta.";await audit(false,{message});return result(rpc.id,error(message));}
});
