import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type Obj=Record<string,unknown>; type Rpc={id?:string|number|null;method?:string;params?:{name?:string;arguments?:Obj}};
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,mcp-protocol-version,mcp-session-id","Access-Control-Allow-Methods":"POST,OPTIONS"};
const header={...cors,"Content-Type":"application/json"};
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,"0")).join("");
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:header});
const result=(id:Rpc["id"],value:unknown)=>out({jsonrpc:"2.0",id:id??null,result:value});
const fail=(id:Rpc["id"],message:string,code=-32000)=>out({jsonrpc:"2.0",id:id??null,error:{code,message}});
const tool=(value:unknown)=>({content:[{type:"text",text:JSON.stringify(value,null,2)}],structuredContent:value});
const error=(message:string)=>({content:[{type:"text",text:message}],isError:true});
const bounded=(value:unknown,fallback=25)=>Math.max(1,Math.min(100,Number(value)||fallback));
const operational=new Set(["admin","operational","operational_supervisor","operational_manager","coordinator"]);
const planningEditors=new Set(["admin","commercial","operational_supervisor","operational_manager"]);
const clonePlanning=(source:any)=>{if(!source||typeof source!=="object")return null;const copy=structuredClone(source);copy.completedBlocks={};copy.store={...(copy.store||{}),unit:"",preStart:"",preEnd:"",inventoryStart:"",inventoryEnd:"",headcount:""};copy.responsibilities=(copy.responsibilities||[]).map((row:any)=>({...row,person:"",notes:""}));copy.logistics={...(copy.logistics||{}),notes:"",transports:(copy.logistics?.transports||[]).map((row:any)=>({...row,date:"",time:"",passengers:"",quantity:"",notes:""})),accommodations:(copy.logistics?.accommodations||[]).map((row:any)=>({...row,guests:"",rooms:"",checkIn:"",checkOut:"",count:"",notes:""}))};for(const key of ["clientEquipment","contagemEquipment"])copy[key]={...(copy[key]||{}),notes:"",rows:(copy[key]?.rows||[]).map((row:any)=>({...row,date:"",quantity:"",status:"Solicitado",notes:""}))};copy.preCount={...(copy.preCount||{}),notes:"",rows:(copy.preCount?.rows||[]).map((row:any)=>({...row,date:"",time:"",team:"",count:"",notes:""}))};copy.days=(copy.days||[]).map((day:any)=>({...day,date:"",headcount:"",notes:"",areas:(day.areas||[]).map((area:any)=>({...area,startsAt:"",headcount:"",notes:"",roles:(area.roles||[]).map((role:any)=>({...role,count:"",names:""})),activities:(area.activities||[]).map((activity:any)=>({...activity,notes:""}))}))}));for(const key of Object.keys(copy.checklists||{}))copy.checklists[key]=(copy.checklists[key]||[]).map((item:any)=>{const next={...item,done:false};delete next.completedAt;delete next.completedBy;return next});return copy};

const tools=[
  ["contagem_overview","Resumo operacional e permissões da conexão.",{},[]],
  ["contagem_list_projects","Lista operações por etapa com paginação.",{status:{type:"string"},search:{type:"string",maxLength:120},limit:{type:"integer",minimum:1,maximum:100},offset:{type:"integer",minimum:0,maximum:10000}},[]],
  ["contagem_get_project","Detalhe consolidado de uma operação.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_get_export_data","Retorna dados completos para gerar PDF, Excel ou relatório.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_list_tasks","Lista tarefas por status, operação ou responsável.",{project_id:{type:"string"},status:{type:"string"},search:{type:"string",maxLength:120},limit:{type:"integer",minimum:1,maximum:100}},[]],
  ["contagem_list_calendar","Lista operações com início de inventário em um intervalo.",{start_date:{type:"string"},end_date:{type:"string"}},[]],
  ["contagem_list_settings","Lista campos, modelos de tarefas e catálogos configuráveis.",{},[]],
  ["contagem_create_request","Cria ou duplica solicitação de forma idempotente.",{idempotency_key:{type:"string"},cnpj:{type:"string"},legal_name:{type:"string"},trade_name:{type:"string"},address:{type:"string"},contact_name:{type:"string"},contact_email:{type:"string"},contact_phone:{type:"string"},inventory_type:{type:"string"},layout_system:{type:"string"},ti_contact_name:{type:"string"},ti_contact_email:{type:"string"},ti_contact_phone:{type:"string"},requires_dimensioning:{type:"boolean"},source_project_id:{type:"string"},field_values:{type:"array",items:{type:"object"}}},["idempotency_key","cnpj","legal_name","contact_name","contact_email"]],
  ["contagem_start_dimensioning","Move uma solicitação para Dimensionamento.",{project_id:{type:"string"}},["project_id"]],
  ["contagem_save_dimensioning","Salva cenários, opção selecionada e visitas.",{project_id:{type:"string"},options:{type:"array",items:{type:"object"}},selected_option_id:{type:["string","null"]},visit_starts:{type:"array",items:{type:"string"}},notes:{type:"string"}},["project_id","options","visit_starts"]],
  ["contagem_complete_dimensioning","Conclui dimensionamento e envia para TI.",{project_id:{type:"string"},notes:{type:"string"}},["project_id"]],
  ["contagem_save_ti","Salva dados técnicos e visita selecionada.",{project_id:{type:"string"},system_name:{type:"string"},ti_contact_name:{type:"string"},ti_contact_email:{type:"string"},ti_contact_phone:{type:"string"},notes:{type:"string"},selected_date_option_id:{type:["string","null"]}},["project_id"]],
  ["contagem_approve_ti","Aprova TI e libera Planejamento.",{project_id:{type:"string"},system_name:{type:"string"},notes:{type:"string"}},["project_id"]],
  ["contagem_save_planning","Salva todos os blocos e checklists.",{project_id:{type:"string"},content:{type:"object"},completion_percentage:{type:"number",minimum:0,maximum:100}},["project_id","content"]],
  ["contagem_approve_planning","Aprova planejamento e conclui operação.",{project_id:{type:"string"},content:{type:"object"},completion_percentage:{type:"number",minimum:0,maximum:100}},["project_id","content","completion_percentage"]],
  ["contagem_sync_tasks","Gera ou recalcula tarefas aplicáveis.",{project_id:{type:"string"},inventory_start:{type:["string","null"]}},["project_id"]],
  ["contagem_update_task","Atualiza responsável, prazo ou status.",{task_id:{type:"string"},status:{type:"string",enum:["pending","in_progress","completed","waived"]},responsible_name:{type:"string",maxLength:160},due_at:{type:["string","null"]},set_due:{type:"boolean"}},["task_id"]],
  ["contagem_upsert_custom_field","Cria ou atualiza campo. Somente admin.",{field_id:{type:["string","null"]},field_key:{type:"string"},label:{type:"string"},required:{type:"boolean"},active:{type:"boolean"},show_when_dimensioning:{type:"boolean"},sort_order:{type:"integer"}},["label"]],
  ["contagem_delete_custom_field","Exclui campo não sistêmico. Somente admin.",{field_id:{type:"string"}},["field_id"]],
  ["contagem_upsert_task_template","Gerencia modelo de tarefa. Somente admin.",{template_id:{type:["string","null"]},title:{type:"string"},description:{type:"string"},inventory_type:{type:"string"},due_days_before_inventory:{type:["integer","null"]},responsible_role:{type:"string"},active:{type:"boolean"},sort_order:{type:"integer"}},["title"]]
].map(([name,description,properties,required])=>({name,title:String(name).replaceAll("_"," "),description,inputSchema:{type:"object",properties,required,additionalProperties:false},annotations:{readOnlyHint:!String(name).match(/_(create|start|save|complete|approve|sync|update|upsert|delete)_?/),destructiveHint:String(name).includes("delete"),idempotentHint:true,openWorldHint:false}}));

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return out({error:"Use POST."},405);
  const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)return out({error:"Bearer obrigatório."},401);
  const url=Deno.env.get("SUPABASE_URL")!;const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
  const {data:connection}=await db.from("contagem_g4os_connections").select("id,owner_user_id,scopes").eq("token_hash",await sha256(token)).eq("active",true).maybeSingle();
  if(!connection)return out({error:"Credencial inválida ou revogada."},401);
  const {data:roles}=await db.from("user_roles").select("role").eq("user_id",connection.owner_user_id);const roleList=(roles??[]).map(row=>String(row.role));
  let rpc:Rpc;try{rpc=await req.json()}catch{return fail(null,"JSON-RPC inválido",-32700)}
  if(rpc.method==="initialize")return result(rpc.id,{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"contagem-ops-mcp",version:"1.0.0"}});
  if(rpc.method==="notifications/initialized")return new Response(null,{status:202,headers:cors});
  if(rpc.method==="tools/list")return result(rpc.id,{tools});
  if(rpc.method!=="tools/call")return fail(rpc.id,"Método não suportado",-32601);
  const name=rpc.params?.name||"";const args=rpc.params?.arguments||{};const started=Date.now();let operation="READ";
  const audit=async(success:boolean,details:Obj={})=>{await db.from("contagem_g4os_events").insert({connection_id:connection.id,actor_user_id:connection.owner_user_id,tool_name:name,operation,success,duration_ms:Date.now()-started,details})};
  try{
    if(name==="contagem_overview"){
      const statuses=["received","awaiting_dimensioning","awaiting_ti","planning","confirmed"];const counts=Object.fromEntries(await Promise.all(statuses.map(async status=>[status,(await db.from("projects").select("id",{count:"exact",head:true}).eq("status",status).is("deleted_at",null)).count??0])));const payload={roles:roleList,scopes:connection.scopes,projects:counts};await audit(true);return result(rpc.id,tool(payload));
    }
    if(name==="contagem_list_projects"){
      let query=db.from("projects").select("id,reference,status,inventory_type,requires_dimensioning,created_at,clients(legal_name,trade_name,cnpj),plannings(content,status)",{count:"exact"}).is("deleted_at",null).order("created_at",{ascending:false}).range(Number(args.offset)||0,(Number(args.offset)||0)+bounded(args.limit)-1);if(args.status)query=query.eq("status",String(args.status));const {data,count,error:queryError}=await query;if(queryError)throw queryError;const search=String(args.search||"").trim().toLocaleLowerCase("pt-BR");const items=(data??[]).filter((item:any)=>!search||[item.reference,item.inventory_type,item.clients?.legal_name,item.clients?.trade_name,item.clients?.cnpj].some(value=>String(value||"").toLocaleLowerCase("pt-BR").includes(search))).map((item:any)=>({id:item.id,reference:item.reference,status:item.status,inventory_type:item.inventory_type,requires_dimensioning:item.requires_dimensioning,created_at:item.created_at,company:item.clients?.legal_name,trade_name:item.clients?.trade_name,cnpj:item.clients?.cnpj,inventory_start:item.plannings?.content?.store?.inventoryStart||null}));await audit(true,{returned:items.length});return result(rpc.id,tool({items,total:count??items.length}));
    }
    if(name==="contagem_get_project"){
      const projectId=String(args.project_id||"");if(!projectId)throw new Error("project_id obrigatório.");const {data,error:queryError}=await db.from("projects").select("*,clients(*),dimensionings(*),dimensioning_options(*),date_options(*),ti_validations(*),plannings(*),project_tasks(*)").eq("id",projectId).maybeSingle();if(queryError||!data)throw new Error("Operação não encontrada.");await audit(true);return result(rpc.id,tool(data));
    }
    if(name==="contagem_list_tasks"){
      let query=db.from("project_tasks").select("id,project_id,title,description,responsible_role,responsible_name,due_at,status,completed_at,projects(reference,status,clients(legal_name))").order("due_at",{ascending:true,nullsFirst:false}).limit(bounded(args.limit));if(args.project_id)query=query.eq("project_id",String(args.project_id));if(args.status)query=query.eq("status",String(args.status));const {data,error:queryError}=await query;if(queryError)throw queryError;const search=String(args.search||"").toLocaleLowerCase("pt-BR");const items=(data??[]).filter((row:any)=>!search||[row.title,row.responsible_name,row.responsible_role,row.projects?.reference,row.projects?.clients?.legal_name].some(value=>String(value||"").toLocaleLowerCase("pt-BR").includes(search)));await audit(true,{returned:items.length});return result(rpc.id,tool({items}));
    }
    if(name==="contagem_list_calendar"){
      const {data,error:queryError}=await db.from("plannings").select("project_id,content,status,projects(reference,status,clients(legal_name))").limit(500);if(queryError)throw queryError;const start=String(args.start_date||"");const end=String(args.end_date||"");const items=(data??[]).filter((row:any)=>{const date=row.content?.store?.inventoryStart||"";return date&&(!start||date>=start)&&(!end||date<=end)}).map((row:any)=>({project_id:row.project_id,reference:row.projects?.reference,company:row.projects?.clients?.legal_name,status:row.projects?.status,inventory_start:row.content?.store?.inventoryStart,inventory_end:row.content?.store?.inventoryEnd,headcount:row.content?.store?.headcount}));await audit(true,{returned:items.length});return result(rpc.id,tool({items}));
    }

    if(name==="contagem_get_export_data"){
      const projectId=String(args.project_id||"");const {data,error:queryError}=await db.from("projects").select("id,reference,status,inventory_type,clients(legal_name,trade_name,cnpj),dimensionings(*),dimensioning_options(*),date_options(*),ti_validations(*),plannings(*),project_tasks(*)").eq("id",projectId).maybeSingle();if(queryError||!data)throw new Error("Operação não encontrada.");await audit(true);return result(rpc.id,tool({generated_at:new Date().toISOString(),project:data}));
    }
    if(name==="contagem_list_settings"){
      const [fields,templates,roleCatalog,activities,equipment,checklists]=await Promise.all([db.from("custom_fields").select("*").eq("entity","project").order("sort_order"),db.from("task_templates").select("*").order("sort_order"),db.from("planning_role_catalog").select("*").order("sort_order"),db.from("planning_activity_catalog").select("*").order("sort_order"),db.from("equipment_catalog").select("*").order("name"),db.from("checklist_templates").select("*,checklist_template_items(*)")]);const firstError=[fields,templates,roleCatalog,activities,equipment,checklists].find(item=>item.error)?.error;if(firstError)throw firstError;await audit(true);return result(rpc.id,tool({custom_fields:fields.data,task_templates:templates.data,role_catalog:roleCatalog.data,activity_catalog:activities.data,equipment_catalog:equipment.data,checklist_templates:checklists.data}));
    }
    operation="WRITE";
    const actor=connection.owner_user_id;
    if(name==="contagem_start_dimensioning"){const {error:e}=await db.rpc("g4os_start_dimensioning",{p_actor_id:actor,p_project_id:String(args.project_id)});if(e)throw e;await audit(true);return result(rpc.id,tool({started:true}));}
    if(name==="contagem_save_dimensioning"){const {error:e}=await db.rpc("g4os_save_dimensioning_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_options:args.options||[],p_selected_option_id:args.selected_option_id||null,p_visit_starts:args.visit_starts||[],p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({saved:true}));}
    if(name==="contagem_complete_dimensioning"){const {error:e}=await db.rpc("g4os_complete_dimensioning",{p_actor_id:actor,p_project_id:String(args.project_id),p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({completed:true}));}
    if(name==="contagem_save_ti"){const {error:e}=await db.rpc("g4os_save_ti_validation_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_system_name:args.system_name||null,p_ti_contact_name:args.ti_contact_name||null,p_ti_contact_email:args.ti_contact_email||null,p_ti_contact_phone:args.ti_contact_phone||null,p_notes:args.notes||null,p_selected_date_option_id:args.selected_date_option_id||null});if(e)throw e;await audit(true);return result(rpc.id,tool({saved:true}));}
    if(name==="contagem_approve_ti"){const {error:e}=await db.rpc("g4os_approve_ti_validation",{p_actor_id:actor,p_project_id:String(args.project_id),p_system_name:args.system_name||null,p_notes:args.notes||null});if(e)throw e;await audit(true);return result(rpc.id,tool({approved:true}));}
    if(name==="contagem_save_planning"){const {data,error:e}=await db.rpc("g4os_save_planning_draft",{p_actor_id:actor,p_project_id:String(args.project_id),p_content:args.content,p_completion_percentage:Number(args.completion_percentage)||0});if(e)throw e;await audit(true);return result(rpc.id,tool({planning_id:data}));}
    if(name==="contagem_approve_planning"){const {error:e}=await db.rpc("g4os_approve_planning",{p_actor_id:actor,p_project_id:String(args.project_id),p_content:args.content,p_completion_percentage:Number(args.completion_percentage)});if(e)throw e;await audit(true);return result(rpc.id,tool({approved:true}));}
    if(name==="contagem_sync_tasks"){const {data,error:e}=await db.rpc("g4os_sync_project_tasks",{p_actor_id:actor,p_project_id:String(args.project_id),p_inventory_start:args.inventory_start||null});if(e)throw e;await audit(true);return result(rpc.id,tool({affected:data}));}
    if(name==="contagem_update_task"){const {data,error:e}=await db.rpc("g4os_update_project_task",{p_actor_id:actor,p_task_id:String(args.task_id),p_status:args.status||null,p_responsible_name:args.responsible_name??null,p_due_at:args.due_at||null,p_set_due:Boolean(args.set_due||Object.prototype.hasOwnProperty.call(args,"due_at"))});if(e)throw e;await audit(true,{task_id:args.task_id});return result(rpc.id,tool(data));}
    if(name==="contagem_upsert_custom_field"){const {data,error:e}=await db.rpc("g4os_upsert_custom_field",{p_actor_id:actor,p_field_id:args.field_id||null,p_field_key:args.field_key||null,p_label:String(args.label||""),p_required:args.required??false,p_active:args.active??true,p_show_when_dimensioning:args.show_when_dimensioning??false,p_sort_order:Number(args.sort_order)||0});if(e)throw e;await audit(true);return result(rpc.id,tool({field_id:data}));}
    if(name==="contagem_delete_custom_field"){const {error:e}=await db.rpc("g4os_delete_custom_field",{p_actor_id:actor,p_field_id:String(args.field_id)});if(e)throw e;await audit(true);return result(rpc.id,tool({deleted:true}));}
    if(name==="contagem_upsert_task_template"){const {data,error:e}=await db.rpc("g4os_upsert_task_template",{p_actor_id:actor,p_template_id:args.template_id||null,p_title:String(args.title||""),p_description:args.description||null,p_inventory_type:args.inventory_type||null,p_due_days_before_inventory:args.due_days_before_inventory??null,p_responsible_role:args.responsible_role||null,p_active:args.active??true,p_sort_order:Number(args.sort_order)||0});if(e)throw e;await audit(true);return result(rpc.id,tool({template_id:data}));}
    if(name==="contagem_create_request"){
      if(!roleList.some(role=>planningEditors.has(role)))throw new Error("Seu perfil não pode criar solicitações.");const key=String(args.idempotency_key||"");if(!/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(key))throw new Error("idempotency_key deve ser um UUID.");let planningContent=null;if(args.source_project_id){const {data:source,error:sourceError}=await db.from("plannings").select("content").eq("project_id",String(args.source_project_id)).maybeSingle();if(sourceError||!source)throw new Error("Planejamento de origem não encontrado.");planningContent=clonePlanning(source.content)}const {data,error:e}=await db.rpc("g4os_create_project_request",{p_actor_id:actor,p_request_key:key,p_cnpj:String(args.cnpj||"").replace(/\D/g,""),p_cnpj_raw:String(args.cnpj||""),p_legal_name:String(args.legal_name||""),p_trade_name:args.trade_name||null,p_address:args.address||null,p_contact_name:String(args.contact_name||""),p_contact_email:String(args.contact_email||""),p_contact_phone:args.contact_phone||null,p_inventory_type:args.inventory_type||null,p_layout_system:args.layout_system||null,p_ti_contact_name:args.ti_contact_name||null,p_ti_contact_email:args.ti_contact_email||null,p_ti_contact_phone:args.ti_contact_phone||null,p_requires_dimensioning:args.requires_dimensioning!==false,p_operational_notes:args.source_project_id?`Modelo copiado de ${args.source_project_id}`:"Criada pelo G4 OS",p_field_values:args.field_values||[],p_planning_content:planningContent});if(e)throw e;await audit(true,{project_id:data});return result(rpc.id,tool({project_id:data}));
    }
    throw new Error("Ferramenta não encontrada.");
  }catch(cause){const message=cause instanceof Error?cause.message:"Falha ao executar ferramenta.";await audit(false,{message});return result(rpc.id,error(message));}
});
