import React,{useEffect,useMemo,useState}from'react';

const appRoles=['admin','commercial','operational_supervisor','operational_manager','operational','ti','coordinator','viewer'];
const roleLabels={admin:'Administrador',commercial:'Comercial',operational_supervisor:'Supervisor operacional',operational_manager:'Gestor operacional',operational:'Operação',ti:'TI',coordinator:'Coordenador',viewer:'Somente leitura'};
const fieldTypes=[['text','Texto'],['textarea','Texto longo'],['number','Número'],['date','Data'],['email','E-mail'],['phone','Telefone'],['select','Lista'],['checkbox','Sim/Não']];
const fieldStages=[['request','Solicitação'],['dimensioning','Dimensionamento'],['ti','TI'],['planning','Planejamento'],['calendar','Calendário']];
const blankField={label:'',field_key:'',field_type:'text',required:false,active:true,stage:'request',show_when_dimensioning:false,sort_order:100,options:[],placeholder:'',help_text:'',system_field:false};
const blankTask={title:'',description:'',inventory_type:'',due_days_before_inventory:'',responsible_role:'',active:true,sort_order:0};
const catalogConfigs={
  roles:{title:'Funções e responsabilidades',description:'Papéis usados na composição das equipes.',itemsKey:'roleItems',blank:{name:'',category:'',active:true,sort_order:0},fields:[['name','Nome'],['category','Categoria'],['sort_order','Ordem','number']]},
  activities:{title:'Atividades',description:'Atividades disponíveis nos dias e áreas.',itemsKey:'activityItems',blank:{name:'',area_type:'',active:true,sort_order:0},fields:[['name','Nome'],['area_type','Tipo de área'],['sort_order','Ordem','number']]},
  equipment:{title:'Equipamentos',description:'Recursos fornecidos pela Contagem ou cliente.',itemsKey:'equipmentItems',blank:{name:'',owner_type:'contagem',active:true},fields:[['name','Nome'],['owner_type','Proprietário','owner']]},
  inventory_types:{title:'Tipos de inventário',description:'Segmentam tarefas, checklists e operações.',itemsKey:'inventoryTypes',blank:{name:'',description:'',active:true,sort_order:0},fields:[['name','Nome'],['description','Descrição'],['sort_order','Ordem','number']]},
  blocks:{title:'Blocos do planejamento',description:'Controlam a estrutura e os gates do planejamento.',itemsKey:'blocks',blank:{block_key:'',label:'',description:'',required_for_completion:false,active:true,sort_order:0},fields:[['label','Rótulo'],['block_key','Chave'],['description','Descrição'],['sort_order','Ordem','number']]},
  workflow_stages:{title:'Etapas adicionais',description:'Organizam o Kanban sem alterar os gates obrigatórios.',itemsKey:'stages',blank:{stage_key:'',label:'',description:'',color:'#5E97FF',active:true,sort_order:60},fields:[['label','Rótulo'],['stage_key','Chave'],['description','Descrição'],['color','Cor'],['sort_order','Ordem','number']]}
};
const tabs=[['forms','Campos'],['operation','Operação'],['automation','Automações'],['access','Pessoas'],['archive','Arquivo']];
const tabInfo={forms:{icon:'Aa',hint:'Formulários e coleta'},operation:{icon:'OP',hint:'Catálogos e fluxo'},automation:{icon:'✓',hint:'Tarefas e checklists'},access:{icon:'@',hint:'Equipe e permissões'},archive:{icon:'↺',hint:'Operações arquivadas'}};

function StatusPill({active=true,protectedItem=false}){return <span className={`admin-status ${active?'is-active':'is-inactive'}`}><i/>{active?'Ativo':'Inativo'}{protectedItem?' · protegido':''}</span>}
function FieldLabel({children,wide=false}){return <label className={wide?'admin-field is-wide':'admin-field'}><span>{children}</span></label>}
function EditorFrame({title,meta,active=true,badge,children,newItem=false}){if(newItem)return <article className="admin-editor is-new"><div className="admin-editor-title"><div><span className="eyebrow">Novo cadastro</span><h3>{title}</h3>{meta&&<p>{meta}</p>}</div></div>{children}</article>;return <details className="admin-record"><summary><div className="admin-record-copy"><b>{title||'Sem nome'}</b><span>{meta||'Clique para revisar e editar'}</span></div><div className="admin-record-meta"><StatusPill active={active}/>{badge&&<span className="base-field">{badge}</span>}<span className="admin-chevron">⌄</span></div></summary><div className="admin-record-body">{children}</div></details>}

function FieldEditor({initial,onSave,onDelete,newItem=false}){
  const [item,setItem]=useState(()=>({...blankField,...initial,options:Array.isArray(initial?.options)?initial.options:[]}));
  useEffect(()=>setItem({...blankField,...initial,options:Array.isArray(initial?.options)?initial.options:[]}),[initial]);
  const update=(key,value)=>setItem(current=>({...current,[key]:value}));
  return <EditorFrame newItem={newItem} title={newItem?'Adicionar campo':item.label} meta={item.system_field?'Campo essencial da operação':'Clique para configurar este campo'} active={item.active!==false} badge={item.system_field?'Campo-base':null}>
    <div className="admin-form-grid">
      <FieldLabel>Rótulo<input value={item.label} onChange={e=>update('label',e.target.value)} placeholder="Ex.: Código da loja"/></FieldLabel>
      <FieldLabel>Chave técnica<input value={item.field_key} onChange={e=>update('field_key',e.target.value)} placeholder="codigo_loja" disabled={!!item.id}/></FieldLabel>
      <FieldLabel>Tipo<select value={item.field_type} onChange={e=>update('field_type',e.target.value)} disabled={item.system_field}>{fieldTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></FieldLabel>
      <FieldLabel>Etapa<select value={item.stage} onChange={e=>setItem(current=>({...current,stage:e.target.value,...(e.target.value!=='request'?{required:false}:{})}))}>{fieldStages.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></FieldLabel>
      <FieldLabel>Ordem<input type="number" value={item.sort_order??0} onChange={e=>update('sort_order',Number(e.target.value))}/></FieldLabel>
      <FieldLabel>Exemplo no campo<input value={item.placeholder||''} onChange={e=>update('placeholder',e.target.value)} placeholder="Texto de exemplo"/></FieldLabel>
      {item.field_type==='select'&&<FieldLabel wide>Opções<input value={(item.options||[]).join(', ')} onChange={e=>update('options',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))} placeholder="Opção A, Opção B, Opção C"/></FieldLabel>}
      <FieldLabel wide>Texto de ajuda<input value={item.help_text||''} onChange={e=>update('help_text',e.target.value)} placeholder="Orientação exibida abaixo do campo"/></FieldLabel>
    </div>
    <div className="admin-options"><label><input type="checkbox" checked={!!item.required} disabled={item.stage!=='request'} onChange={e=>update('required',e.target.checked)}/> Obrigatório</label><label><input type="checkbox" checked={!!item.active} onChange={e=>update('active',e.target.checked)}/> Ativo</label><label><input type="checkbox" checked={!!item.show_when_dimensioning} onChange={e=>update('show_when_dimensioning',e.target.checked)}/> Exibir apenas quando houver dimensionamento</label></div>
    <div className="admin-editor-actions"><button type="button" className="primary" onClick={()=>onSave(item)}>Salvar campo</button>{item.id&&!item.system_field&&<button type="button" className="delete" onClick={()=>onDelete(item)}>Excluir campo</button>}</div>
  </EditorFrame>
}

function TaskEditor({initial,onSave,newItem=false}){
  const [item,setItem]=useState(()=>({...blankTask,...initial}));useEffect(()=>setItem({...blankTask,...initial}),[initial]);const update=(key,value)=>setItem(current=>({...current,[key]:value}));
  return <EditorFrame newItem={newItem} title={newItem?'Adicionar modelo de tarefa':item.title} meta={`${item.inventory_type||'Todos os inventários'} · ${item.due_days_before_inventory===null||item.due_days_before_inventory===''?'Prazo livre':`${item.due_days_before_inventory} dia(s) antes`}`} active={item.active!==false} badge={item.notion_origin?'Origem Notion':null}>
    <div className="admin-form-grid"><FieldLabel wide>Nome da tarefa<input value={item.title} onChange={e=>update('title',e.target.value)} placeholder="Nome objetivo da tarefa"/></FieldLabel><FieldLabel>Tipo de inventário<input value={item.inventory_type||''} onChange={e=>update('inventory_type',e.target.value)} placeholder="Vazio = todos"/></FieldLabel><FieldLabel>Dias antes<input type="number" min="0" value={item.due_days_before_inventory??''} onChange={e=>update('due_days_before_inventory',e.target.value===''?null:Number(e.target.value))}/></FieldLabel><FieldLabel>Papel responsável<input value={item.responsible_role||''} onChange={e=>update('responsible_role',e.target.value)}/></FieldLabel><FieldLabel>Ordem<input type="number" value={item.sort_order??0} onChange={e=>update('sort_order',Number(e.target.value))}/></FieldLabel><FieldLabel wide>Descrição / critério<textarea value={item.description||''} onChange={e=>update('description',e.target.value)} placeholder="O que precisa acontecer para concluir esta tarefa?"/></FieldLabel></div>
    <div className="admin-options"><label><input type="checkbox" checked={!!item.active} onChange={e=>update('active',e.target.checked)}/> Ativo</label></div><div className="admin-editor-actions"><button type="button" className="primary" onClick={()=>onSave(item)}>Salvar modelo</button></div>
  </EditorFrame>
}

function CatalogEditor({kind,items=[],onSave}){
  const config=catalogConfigs[kind];const [creating,setCreating]=useState(false);
  return <section className="admin-subsection"><div className="admin-subsection-head"><div><h2>{config.title}</h2><p>{config.description}</p></div><button type="button" onClick={()=>setCreating(value=>!value)}>{creating?'Cancelar':'Adicionar'}</button></div>{creating&&<CatalogRow newItem kind={kind} initial={config.blank} config={config} onSave={async item=>{await onSave(kind,item);setCreating(false)}}/>}<div className="admin-record-list">{items.map(item=><CatalogRow key={item.id} kind={kind} initial={item} config={config} onSave={value=>onSave(kind,value)}/>)}</div></section>
}
function CatalogRow({kind,initial,config,onSave,newItem=false}){
  const [item,setItem]=useState(()=>({...config.blank,...initial}));useEffect(()=>setItem({...config.blank,...initial}),[initial]);const update=(key,value)=>setItem(current=>({...current,[key]:value}));const title=item.name||item.label||'Novo item';const meta=item.category||item.area_type||item.description||item.owner_type||item.block_key||item.stage_key||'Catálogo operacional';
  return <EditorFrame newItem={newItem} title={title} meta={meta} active={item.active!==false} badge={item.system_stage?'Protegido':item.notion_origin?'Origem Notion':null}><div className="admin-form-grid">{config.fields.map(([key,label,type])=>type==='owner'?<FieldLabel key={key}>{label}<select value={item[key]||'contagem'} onChange={e=>update(key,e.target.value)}><option value="contagem">Contagem</option><option value="client">Cliente</option></select></FieldLabel>:<FieldLabel key={key} wide={key==='description'}>{label}<input type={type||'text'} value={item[key]??''} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)} disabled={(key==='stage_key'&&item.system_stage)||(key==='block_key'&&!!item.id)}/></FieldLabel>)}</div><div className="admin-options"><label><input type="checkbox" checked={item.active!==false} onChange={e=>update('active',e.target.checked)}/> Ativo</label>{kind==='blocks'&&<label><input type="checkbox" checked={!!item.required_for_completion} onChange={e=>update('required_for_completion',e.target.checked)}/> Obrigatório para concluir</label>}</div><div className="admin-editor-actions"><button type="button" className="primary" onClick={()=>onSave(item)}>Salvar alteração</button></div></EditorFrame>
}

function ChecklistEditor({initial,onSave,newItem=false}){
  const normalize=value=>({...value,items:[...(value.checklist_template_items||value.items||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0))});const [item,setItem]=useState(()=>normalize(initial));useEffect(()=>setItem(normalize(initial)),[initial]);const update=(key,value)=>setItem(current=>({...current,[key]:value}));const setItems=text=>update('items',text.split('\n').map((line,index)=>({label:line.trim(),required:true,sort_order:index})).filter(row=>row.label));
  return <EditorFrame newItem={newItem} title={newItem?'Adicionar checklist':item.name} meta={`${item.checklist_type==='pre_inventory_visit'?'Pré-inventário':item.checklist_type==='final'?'Conferência final':'Planejamento'} · ${(item.items||[]).length} item(ns)`} active={item.active!==false}><div className="admin-form-grid"><FieldLabel wide>Nome<input value={item.name||''} onChange={e=>update('name',e.target.value)}/></FieldLabel><FieldLabel>Momento<select value={item.checklist_type||'planning'} onChange={e=>update('checklist_type',e.target.value)}><option value="pre_inventory_visit">Pré-inventário</option><option value="planning">Planejamento</option><option value="final">Conferência final</option></select></FieldLabel><FieldLabel>Tipo de inventário<input value={item.inventory_type||''} onChange={e=>update('inventory_type',e.target.value)} placeholder="Vazio = todos"/></FieldLabel><FieldLabel wide>Itens<textarea className="admin-items-textarea" value={(item.items||[]).map(row=>row.label).join('\n')} onChange={e=>setItems(e.target.value)} placeholder="Digite um item por linha"/></FieldLabel></div><div className="admin-options"><label><input type="checkbox" checked={item.active!==false} onChange={e=>update('active',e.target.checked)}/> Ativo</label></div><div className="admin-editor-actions"><button type="button" className="primary" onClick={()=>onSave(item)}>Salvar checklist</button></div></EditorFrame>
}

function RoleChecks({roles=[],onChange}){return <div className="role-checks">{appRoles.map(role=><label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={e=>onChange(e.target.checked?[...new Set([...roles,role])]:roles.filter(item=>item!==role))}/>{roleLabels[role]}</label>)}</div>}
function UserRow({user,onSave}){const [draft,setDraft]=useState({...user,roles:user.roles||[]});useEffect(()=>setDraft({...user,roles:user.roles||[]}),[user]);return <EditorFrame title={draft.full_name||draft.email} meta={draft.job_title||draft.email} active={draft.active!==false}><div className="admin-form-grid"><FieldLabel>Nome completo<input value={draft.full_name||''} onChange={e=>setDraft(current=>({...current,full_name:e.target.value}))}/></FieldLabel><FieldLabel>Cargo / função<input value={draft.job_title||''} onChange={e=>setDraft(current=>({...current,job_title:e.target.value}))} placeholder="Ex.: Coordenador de inventário"/></FieldLabel><FieldLabel>E-mail<input value={draft.email||''} disabled/></FieldLabel></div><RoleChecks roles={draft.roles} onChange={roles=>setDraft(current=>({...current,roles}))}/><div className="admin-options"><label><input type="checkbox" checked={draft.active!==false} onChange={e=>setDraft(current=>({...current,active:e.target.checked}))}/> Acesso ativo</label></div><div className="admin-editor-actions"><button type="button" className="primary" onClick={()=>onSave(draft)}>Salvar acesso</button></div></EditorFrame>}
function UsersAdmin({users=[],onInvite,onSave}){const [inviting,setInviting]=useState(false);const [invite,setInvite]=useState({email:'',full_name:'',job_title:'',roles:['viewer']});return <section className="admin-subsection"><div className="admin-subsection-head"><div><h2>Usuários e perfis</h2><p>Convide pessoas e controle o nível de acesso de cada uma.</p></div><button type="button" onClick={()=>setInviting(value=>!value)}>{inviting?'Cancelar':'Convidar usuário'}</button></div>{inviting&&<EditorFrame newItem title="Convidar usuário" meta="O convite será enviado por e-mail"><div className="admin-form-grid"><FieldLabel>Nome completo<input value={invite.full_name} onChange={e=>setInvite(current=>({...current,full_name:e.target.value}))}/></FieldLabel><FieldLabel>Cargo / função<input value={invite.job_title} onChange={e=>setInvite(current=>({...current,job_title:e.target.value}))} placeholder="Ex.: Coordenador de inventário"/></FieldLabel><FieldLabel>E-mail<input type="email" value={invite.email} onChange={e=>setInvite(current=>({...current,email:e.target.value}))}/></FieldLabel></div><RoleChecks roles={invite.roles} onChange={roles=>setInvite(current=>({...current,roles}))}/><div className="admin-editor-actions"><button type="button" className="primary" onClick={async()=>{await onInvite(invite);setInvite({email:'',full_name:'',job_title:'',roles:['viewer']});setInviting(false)}}>Enviar convite</button></div></EditorFrame>}<div className="admin-record-list">{users.map(user=><UserRow key={user.id} user={user} onSave={onSave}/>)}</div></section>}

function SectionHeader({eyebrow,title,description,action}){return <div className="admin-page-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div>{action}</div>}

export default function AdminSettings({data,onSaveField,onDeleteField,onSaveTask,onSaveCatalog,onSaveChecklist,onInviteUser,onSaveUser,onRestoreProject}){
  const [tab,setTab]=useState('forms');const [newField,setNewField]=useState(false);const [newTask,setNewTask]=useState(false);const [newChecklist,setNewChecklist]=useState(false);const fields=useMemo(()=>[...(data.fields||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),[data.fields]);
  const counts={fields:fields.filter(field=>field.active).length,tasks:(data.catalogs?.tasks||[]).filter(item=>item.active).length,users:(data.users||[]).filter(user=>user.active).length,archived:(data.archivedRequests||[]).length};
  const tabCounts={forms:counts.fields,automation:counts.tasks,access:counts.users,archive:counts.archived};
  return <div className="admin-settings"><header className="admin-settings-header"><div><span className="eyebrow">Configurações</span><h2>Espaço de trabalho</h2><p>Organize formulários, operação, automações e pessoas sem alterar código.</p></div><span className="admin-save-note"><i/>Alterações aplicadas à plataforma e ao G4 OS</span></header>
    <div className="admin-settings-layout"><nav className="admin-tabs" aria-label="Áreas de administração"><span className="admin-nav-label">Configurações</span>{tabs.map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><span className="admin-tab-icon">{tabInfo[id].icon}</span><span className="admin-tab-copy"><b>{label}</b><small>{tabInfo[id].hint}</small></span>{tabCounts[id]!==undefined?<em>{tabCounts[id]}</em>:null}</button>)}<div className="admin-nav-help"><b>Edição progressiva</b><span>Os registros ficam fechados. Abra somente o item que deseja alterar.</span></div></nav>
    <div className="admin-tab-content">
      {tab==='forms'&&<><SectionHeader eyebrow="Formulários" title="Campos configuráveis" description="Escolha o tipo, a etapa e as regras de cada informação coletada." action={<button type="button" className="primary" onClick={()=>setNewField(value=>!value)}>{newField?'Cancelar':'Adicionar campo'}</button>}/>{newField&&<FieldEditor newItem initial={blankField} onSave={async item=>{await onSaveField(item);setNewField(false)}}/>}<div className="admin-record-list">{fields.map(field=><FieldEditor key={field.id} initial={field} onSave={onSaveField} onDelete={onDeleteField}/>)}</div></>}
      {tab==='operation'&&<><SectionHeader eyebrow="Estrutura operacional" title="Catálogos e fluxo" description="Defina o vocabulário e a estrutura usados em toda a plataforma."/>{Object.keys(catalogConfigs).map(kind=><CatalogEditor key={kind} kind={kind} items={data.catalogs?.[catalogConfigs[kind].itemsKey]||[]} onSave={onSaveCatalog}/>)}</>}
      {tab==='automation'&&<><SectionHeader eyebrow="Automação" title="Tarefas e checklists" description="Transforme regras recorrentes em tarefas e gates automáticos." action={<div className="admin-head-actions"><button type="button" onClick={()=>setNewChecklist(value=>!value)}>Novo checklist</button><button type="button" className="primary" onClick={()=>setNewTask(value=>!value)}>Nova tarefa</button></div>}/>{newTask&&<TaskEditor newItem initial={blankTask} onSave={async item=>{await onSaveTask(item);setNewTask(false)}}/>}{newChecklist&&<ChecklistEditor newItem initial={{name:'',checklist_type:'planning',inventory_type:'',active:true,items:[]}} onSave={async item=>{await onSaveChecklist(item);setNewChecklist(false)}}/>}<section className="admin-subsection"><div className="admin-subsection-head"><div><h2>Modelos de tarefas</h2><p>Regras de prazo e responsabilidade por tipo de inventário.</p></div></div><div className="admin-record-list">{(data.catalogs?.tasks||[]).map(task=><TaskEditor key={task.id} initial={task} onSave={onSaveTask}/>)}</div></section><section className="admin-subsection"><div className="admin-subsection-head"><div><h2>Templates de checklist</h2><p>Itens usados nos gates de pré-inventário, planejamento e conclusão.</p></div></div><div className="admin-record-list">{(data.catalogs?.checklistItems||data.catalogs?.checklists||[]).map(template=><ChecklistEditor key={template.id} initial={template} onSave={onSaveChecklist}/>)}</div></section></>}
      {tab==='access'&&<><SectionHeader eyebrow="Segurança" title="Usuários e permissões" description="Mantenha apenas os acessos necessários para cada papel."/><UsersAdmin users={data.users||[]} onInvite={onInviteUser} onSave={onSaveUser}/></>}
      {tab==='archive'&&<><SectionHeader eyebrow="Lifecycle" title="Operações arquivadas" description="Restaure operações preservando o histórico e a trilha de auditoria."/><div className="admin-record-list">{counts.archived?(data.archivedRequests||[]).map(project=><article className="admin-archive-row" key={project.id}><div><b>{project.company_name}</b><span>{project.reference||'Sem referência'} · arquivada em {project.deleted_at?new Date(project.deleted_at).toLocaleString('pt-BR'):'data não informada'}</span></div><button type="button" onClick={()=>onRestoreProject(project.id)}>Restaurar operação</button></article>):<div className="admin-empty"><b>Nenhuma operação arquivada</b><span>Quando uma operação for arquivada, ela aparecerá aqui para restauração.</span></div>}</div></>}
    </div></div>
  </div>
}
