create extension if not exists pgcrypto;
create type project_status as enum ('received','awaiting_dates','awaiting_dimensioning','awaiting_ti','planning','confirmed','cancelled');
create table clients (id uuid primary key default gen_random_uuid(), cnpj text unique not null, legal_name text not null, trade_name text, address text, created_at timestamptz default now());
create table client_contacts (id uuid primary key default gen_random_uuid(), client_id uuid references clients(id) on delete cascade, name text not null, email text, phone text, is_primary boolean default true);
create table custom_fields (id uuid primary key default gen_random_uuid(), entity text not null default 'project', field_key text unique not null, label text not null, field_type text not null default 'text', required boolean default false, active boolean default true, sort_order integer default 0, created_at timestamptz default now());
create table projects (id uuid primary key default gen_random_uuid(), reference text unique not null default ('INV-'||to_char(now(),'YYYY')||'-'||upper(substr(gen_random_uuid()::text,1,6))), client_id uuid references clients(id), inventory_type text, layout_system text, ti_contact_name text, ti_contact_email text, ti_contact_phone text, requires_dimensioning boolean default true, status project_status not null default 'received', created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table project_field_values (id uuid primary key default gen_random_uuid(), project_id uuid references projects(id) on delete cascade, field_id uuid references custom_fields(id), value jsonb, unique(project_id,field_id));
create table date_options (id uuid primary key default gen_random_uuid(), project_id uuid references projects(id) on delete cascade, option_number smallint check(option_number between 1 and 2), starts_at timestamptz not null, proposed_by uuid, status text default 'proposed', unique(project_id,option_number));
create table dimensionings (id uuid primary key default gen_random_uuid(), project_id uuid unique references projects(id) on delete cascade, priority integer default 0, status text default 'open', assigned_to uuid, opened_at timestamptz default now(), completed_at timestamptz);
create table dimensioning_options (id uuid primary key default gen_random_uuid(), dimensioning_id uuid references dimensionings(id) on delete cascade, title text not null, days integer, team_size integer, details jsonb default '{}'::jsonb, approved boolean default false, approved_by uuid, approved_at timestamptz);
create table ti_validations (id uuid primary key default gen_random_uuid(), project_id uuid references projects(id) on delete cascade, status text default 'pending', notes text, validated_by uuid, validated_at timestamptz);
create table plannings (id uuid primary key default gen_random_uuid(), project_id uuid unique references projects(id) on delete cascade, content jsonb not null default '{}'::jsonb, version integer default 1, status text default 'draft', approved_by uuid, approved_at timestamptz, updated_at timestamptz default now());
create table audit_logs (id bigint generated always as identity primary key, entity text not null, entity_id uuid not null, action text not null, before_data jsonb, after_data jsonb, actor_id uuid, created_at timestamptz default now());
alter table clients enable row level security; alter table client_contacts enable row level security; alter table projects enable row level security; alter table custom_fields enable row level security; alter table project_field_values enable row level security; alter table date_options enable row level security; alter table dimensionings enable row level security; alter table dimensioning_options enable row level security; alter table ti_validations enable row level security; alter table plannings enable row level security; alter table audit_logs enable row level security;
-- Criar políticas por perfil antes de abrir o acesso dos usuários autenticados.